# Generated by Django 6.0.4 on 2026-06-10 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_index=True, unique=True, verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, max_length=150, null=True, verbose_name='Имя пользователя Telegram')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Телефон')),
                ('language', models.CharField(default='ru', max_length=10, verbose_name='Язык')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(default='Принт Магазин', max_length=100, verbose_name='Название магазина')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='Логотип')),
                ('contacts', models.TextField(blank=True, verbose_name='Контакты')),
                ('manager_telegram', models.CharField(blank=True, help_text='Например: @manager_username или ссылка', max_length=100, verbose_name='Telegram менеджера')),
                ('currency', models.CharField(default='RUB', max_length=10, verbose_name='Валюта')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Минимальная сумма заказа')),
                ('welcome_text', models.TextField(blank=True, verbose_name='Текст приветствия')),
                ('about_text', models.TextField(blank=True, verbose_name='Текст о компании')),
                ('admin_chat_id', models.CharField(blank=True, help_text='Telegram ID чата/канала или администратора для отправки уведомлений о заказах и чеках', max_length=50, verbose_name='Telegram ID чата уведомлений')),
            ],
            options={
                'verbose_name': 'Настройки магазина',
                'verbose_name_plural': 'Настройки магазина',
            },
        ),
    ]
