# Generated by Django 6.0.4 on 2026-06-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_client_is_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='about_text_uz',
            field=models.TextField(blank=True, verbose_name='Текст о компании (UZ)'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='welcome_text_uz',
            field=models.TextField(blank=True, verbose_name='Текст приветствия (UZ)'),
        ),
    ]
