# Generated by Django 6.0.4 on 2026-06-10 12:10

import apps.orders.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название (например, Сбербанк)')),
                ('card_number', models.CharField(max_length=50, verbose_name='Номер карты/счета')),
                ('receiver_name', models.CharField(max_length=200, verbose_name='Имя получателя')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Способ оплаты',
                'verbose_name_plural': 'Способы оплаты',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='users.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('design_file', models.FileField(upload_to='designs/cart/', verbose_name='Файл макета')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.cart', verbose_name='Корзина')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.color', verbose_name='Цвет')),
                ('print_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.printposition', verbose_name='Место нанесения принта')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Товар')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.size', verbose_name='Размер')),
            ],
            options={
                'verbose_name': 'Товар в корзине',
                'verbose_name_plural': 'Товары в корзине',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(default=apps.orders.models.generate_order_number, max_length=50, unique=True, verbose_name='Номер заказа')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО получателя')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('address', models.TextField(verbose_name='Адрес доставки')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Итоговая сумма')),
                ('status', models.CharField(choices=[('NEW', 'Новый'), ('WAITING_PAYMENT', 'Ожидает оплаты'), ('RECEIPT_PENDING', 'Чек отправлен'), ('PAID', 'Оплачен'), ('IN_PRODUCTION', 'В производстве'), ('PRINTED', 'Напечатан'), ('PACKED', 'Упакован'), ('SHIPPED', 'Отправлен'), ('DELIVERED', 'Доставлен'), ('COMPLETED', 'Завершен'), ('CANCELLED', 'Отменен')], default='NEW', max_length=30, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('design_file', models.FileField(upload_to='designs/orders/', verbose_name='Файл макета')),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за единицу (с принтом)')),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.color', verbose_name='Цвет')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Заказ')),
                ('print_position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.printposition', verbose_name='Место нанесения принта')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product', verbose_name='Товар')),
                ('size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.size', verbose_name='Размер')),
            ],
            options={
                'verbose_name': 'Товар в заказе',
                'verbose_name_plural': 'Товары в заказе',
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='receipts/', verbose_name='Фото чека')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Подтвержден'), ('rejected', 'Отклонен')], default='pending', max_length=20, verbose_name='Статус проверки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружен')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Чек об оплате',
                'verbose_name_plural': 'Чеки об оплате',
            },
        ),
    ]
