# Generated by Django 6.0.6 on 2026-06-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='design_file_2',
            field=models.FileField(blank=True, null=True, upload_to='designs/cart/', verbose_name='Второй макет (например, сзади)'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='design_file_2',
            field=models.FileField(blank=True, null=True, upload_to='designs/orders/', verbose_name='Второй макет (например, сзади)'),
        ),
    ]
