# Generated by Django 6.0.6 on 2026-06-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='printposition',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='print_positions/', verbose_name='Изображение-схема'),
        ),
    ]
