# Generated by Django 6.0.6 on 2026-06-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_printposition_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='printposition',
            name='requires_multiple_designs',
            field=models.BooleanField(default=False, verbose_name='Требует два макета (например, спереди и сзади)'),
        ),
    ]
