# Generated by Django 6.0.4 on 2026-06-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_printposition_requires_multiple_designs'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_uz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название (UZ)'),
        ),
        migrations.AddField(
            model_name='color',
            name='name_uz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Цвет (UZ)'),
        ),
        migrations.AddField(
            model_name='printposition',
            name='name_uz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название места (UZ)'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Описание (UZ)'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название (UZ)'),
        ),
    ]
