# Generated by Django 6.0.4 on 2026-06-15 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category_name_uz_color_name_uz_printposition_name_uz_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('title_uz', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название (UZ)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('description_uz', models.TextField(blank=True, null=True, verbose_name='Описание (UZ)')),
                ('image', models.ImageField(upload_to='portfolio/', verbose_name='Фото готового изделия')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Готовое изделие (Портфолио)',
                'verbose_name_plural': 'Готовые изделия (Портфолио)',
            },
        ),
    ]
